spring:
  #from spring boot : Connecting to Elasticsearch using REST clients
#  elasticsearch:
#    rest:
#      uris: http://127.0.0.1:9200
  #Connecting to Elasticsearch using Reactive REST clients
  data:
    elasticsearch:
      client:
        reactive:
          endpoints: es.my.com:30950
          use-ssl: true
          username: elastic
          password: aa0F58v41z4FQF5dVQ463cne
#      repositories:
#        enabled: true
#          username:
#          password: