# 创建一个学生
GET http://localhost:9090/elastic-test/hlTest/create/async/Yang2

###

# find a student by index and id
GET http://localhost:9090/elastic-test/hlTest/source/student/EYyuWXkBNLB9I-2x1q_9
###


# delete a student by index and id
DELETE http://localhost:9090/elastic-test/hlTest/source/student/PvfUZHkBCAARuvYnYJAc
###

# find a student by index and id (exclude desc filed)
GET http://localhost:9090/elastic-test/hlTest/source/student/EYyuWXkBNLB9I-2x1q_9/excludeDesc
###

# create school
POST http://localhost:9090/elastic-test/spring/school
Content-Type: application/json


{
  "name": "WuHan school",
  "introduction": "南京市WuHan小学。"
}

###

# find a school
GET http://localhost:9090/elastic-test/spring/school/zfeyZHkBCAARuvYnTYyX
###

# delete by id
DELETE http://localhost:9090/elastic-test/spring/school/zfeyZHkBCAARuvYnTYyX

###