version: '2.2'
services:
  es01:
    image: elasticsearch-plugins:7.9.3
#    image: elasticsearch:7.9.3
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
#    volumes:
#      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  kibana:
    image: kibana:7.9.3
    container_name: kibana
    ports:
      - 5601:5601
    volumes:
      - ./nodes/kibana.yml:/usr/share/kibana/config/kibana.yml:rw
    #      - /etc/localtime:/etc/localtime
    depends_on:
      - es01
    networks:
      - elastic

networks:
  elastic:
    driver: bridge